### ISSUE TITLE
Missing Attribute

### ISSUE THREAD

**Issue by sokadavi** [williamnavaraj/ipyturtle3#2]
Hey there,

i got a "Attribute Error" saying that the class "Canvas" is missing the attribute size.

Adding self.size = [width, height] to the class solved the problem.

Thanks for you work!

**Comment by williamnavaraj** [comment]
Thanks @sokadavi . Could you provide the code snippet to replicate this issue?

**Comment by sokadavi** [comment]
```ipyturtle_snippet.py
import ipyturtle3 as turtle
from ipyturtle3 import hold_canvas
        
myCanvas = turtle.Canvas(width=400,height=400)
display(myCanvas)
myTS = turtle.TurtleScreen(myCanvas)
myTS.clear()
myTS.bgcolor("lightgreen")
myTurtle = turtle.Turtle(myTS)

myTurtle.forward(100)

**Comment by sokadavi** [comment]
> 

Run in Jupyter Notebook 6.4.5

**Comment by williamnavaraj** [comment]
I ran the code in notebook server 6.4.5. I am not able to replicate this issue. It runs fine. Are you sure this code is throwing "Attribute Error". If so at what line? What is your python/kernel version?

**Comment by sokadavi** [comment]
Python Version 3.9.7
Ipykernel version 6.4.1

Seems like there is a problem with super().__init__()

```---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_12412/533511689.py in <module>
     12 myCanvas = turtle.Canvas(width=400,height=400)
     13 display(myCanvas)
---> 14 myTS = turtle.TurtleScreen(myCanvas)
     15 myTS.clear()
     16 myTS.bgcolor("lightgreen")

C:\ProgramData\Anaconda3\lib\site-packages\ipyturtle3\ipyturtle3.py in __init__(self, cv, mode, colormode, delay)
    229                  colormode=_CFG["colormode"], delay=_CFG["delay"]):
    230         self.cv = cv
--> 231         w = int(self.cv.cget("width"))
    232         h = int(self.cv.cget("height"))
    233         self.cv.config(scrollregion=(-w // 2, -h // 2, w // 2, h // 2))

C:\ProgramData\Anaconda3\lib\site-packages\ipyturtle3\ipyturtle3.py in cget(self, what)
    112 
    113     def cget(self, what="width"):
--> 114         (self.canvwidth, self.canvheight) = self.size
    115         if what == "width":
    116             return self.canvwidth

AttributeError: 'Canvas' object has no attribute 'size'

**Comment by sokadavi** [comment]
I found the problem. What version of ipycanvas do you use? My installed version of ipycanvas is 0.12. In the newest pypi version the author dropped the size attribute. You have to set the width and height directly. 

Example from the ipycanvas docs:
```from ipycanvas import Canvas
canvas = Canvas(width=100, height=50)
```
I compared version 0.10 and version 0.12 in the github repo. The size property got dropped.
https://github.com/martinRenou/ipycanvas/

**Comment by williamnavaraj** [comment]
Thank you. This is sorted now in the latest update.
