### ISSUE TITLE
Pensize / width does not change line thickness

### ISSUE THREAD

**Issue by roncon** [williamnavaraj/ipyturtle3#3]
Changing the turtle.pensize or turtle.width doesn't actually change the size of the lines being drawn. I found after changing the pen resizemode to "auto" allows the turtle to change size, but it still doesn't change the thickness. Ran the same code in console (after swapping to original turtle import) and it works fine. 

![ipyturtle3](https://user-images.githubusercontent.com/4826415/171970190-e889a27e-565a-4f15-bdb7-98a7c2ec6b80.png)

**Comment by williamnavaraj** [comment]
Thank you. This is sorted now.
