### ISSUE TITLE
Doesn't work in Colab

### ISSUE THREAD

**Issue by cayhorstmann** [williamnavaraj/ipyturtle3#4]
I put the demo program into Colab (https://colab.research.google.com/drive/1OjWZIOk7KgjdhdgKp7G5N5aW_jXfmfO8#scrollTo=3O6RXN-8fuZi), and the program hangs.

**Comment by williamnavaraj** [comment]
It seems to work with `ipycanvas==0.13` but not with `ipycanvas==0.13.1`. 

I have raised this issue there:
martinRenou/ipycanvas#318

Until it is fixed, the workaround is:
To use `!pip install ipycanvas==0.13` after installing ipyturtle3.
