### ISSUE TITLE
Doesn't Work in Jupyter Lab

### ISSUE THREAD

**Issue by hchesser** [williamnavaraj/ipyturtle3#7]
When I run an example similar to the one provided in your Demo, I get:

[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'CanvasModel' from module 'ipycanvas'
loadClass@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.a63a8d293fb35a52dc25.js?v=a63a8d293fb35a52dc25:1:74936
loadModelClass@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:10729
_make_model@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:7517

**Comment by hchesser** [comment]
Sorry, forgot to mention I'm using Lab version 3.6.3

**Comment by williamnavaraj** [comment]
@hchesser : What version of ipycanvas do you have?

**Comment by hchesser** [comment]
I do a conda list and I get 0.13.1 - should I try updating?

Hmm - the version I have - 0.13.1 - is the current version according to PyPI.

Ah - I see your issue over on the ipycanvas github for Google colab...

Weird, 
1.  I did a conda install ipycanvas=0.13 (intending to downgrade) - it installed what I think is the same version (0.13.1), but from conda-forge
2. When I do a conda list, it gives me 0.13.1 but now its conda-forge as the source (it was pypi before)
3.  I re-run my notebook with jupyter lab and it works now.

**Comment by hchesser** [comment]
Hmm - the version I have 0.13.1 the current version according to PyPI.

**Comment by hchesser** [comment]
Ah - I see your issue over on the ipycanvas page for Google colab...

**Comment by hchesser** [comment]
Weird, 
1.  I did a conda install ipycanvas=0.13 (intending to downgrade) - it installed what I think is the same version (0.13.1), but from conda-forge
2. 2.  When I do a conda list, it gives me 0.13.1 but now its conda-forge as the source (it was pypi before)
3.  I re-run my notebook with jupyter lab and it works now.

**Comment by williamnavaraj** [comment]
Cheers! Glad it works now @hchesser.
